### ISSUE TITLE
Error while running bender from CLI

### ISSUE THREAD

**Issue by Comandeer** [benderjs/benderjs#260] opened 2017-05-12 13:18 UTC
```
error: [middleware-jobs]  TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1431:5)
    at processFile (/Users/comandeer/repos/ckeditor/ckeditor-dev/node_modules/benderjs-coverage/lib/preprocessor.js:33:10)
    at runTask (/Users/comandeer/repos/benderjs/node_modules/when/pipeline.js:37:16)
    at /Users/comandeer/repos/benderjs/node_modules/when/pipeline.js:42:12
    at tryCatchResolve (/Users/comandeer/repos/benderjs/node_modules/when/lib/apply.js:46:23)
    at callAndResolve (/Users/comandeer/repos/benderjs/node_modules/when/lib/apply.js:30:12)
    at callAndResolveNext (/Users/comandeer/repos/benderjs/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/Users/comandeer/repos/benderjs/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/Users/comandeer/repos/benderjs/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/Users/comandeer/repos/benderjs/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/Users/comandeer/repos/benderjs/node_modules/when/lib/apply.js:34:12)
```

This error is shown for probably every runned test.

**Comment by mlewand** [comment] 2017-06-14 11:54
I can confirm that and it's a coverage plugin issue. Actually that's a duplicate of benderjs/benderjs-coverage#4.

**Closed by mlewand** 2017-06-14 11:54 UTC
Labels: bug
