### ISSUE TITLE
JS error thrown in the dashboard

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#230] opened 2015-05-14 10:22 UTC
Bender 0.2.3. When I load the dashboard in IE9 I get:

```
SCRIPT5007: Unable to get value of the property 'addClass': object is null or undefined 
main.js, line 93 character 4
```

Note - it's not a stable issue. It happens to me occasionally, more frequently when I refresh the page rather than open a new one. I also could not reproduce this on IE8.

**Comment by Reinmar** [comment] 2015-05-20 13:15
Just saw the same error on Chrome.

**Comment by scofalik** [comment] 2015-08-20 08:10
I cannot reproduce it on either Chrome or IE9. The bug's description is too short to try to find and fix it. There are two `main.js` files that could be referenced in bug description. Only one of them has `addClass` string:
```
App._toggleHeader = function() {
		if ( !App.$fixedHeader ) {
			return;
		}

		var supportPageOffset = window.pageYOffset !== undefined,
			isCSS1Compat = ( ( document.compatMode || '' ) === 'CSS1Compat' );

		// pageYOffset is available
		if ( supportPageOffset ? window.pageYOffset :
			// standards-compliant mode is enabled
			isCSS1Compat ? document.documentElement.scrollTop :
			// otherwise use body.scrollTop
			document.body.scrollTop && App.$fixedHeader.hasClass( 'hidden' ) ) {
			App.$fixedHeader.removeClass( 'hidden' );
		} else {
			App.$fixedHeader.addClass( 'hidden' );
		}
	};
```

It's impossible to reach `.addClass` if `App.$fixedHeader` is `undefined` or `null`. Notice, that the `if ( !App.$fixedHeader ) {` statement has been added on 6th Jun, so after you submited the issue. I assume this issue got fixed by it.

**Closed by scofalik** 2015-08-20 08:10 UTC

**Comment by Reinmar** [comment] 2015-08-20 08:47
I can't reproduce it any more. I've seen it recently still, but perhaps v0.3.0 fixed it.
