### ISSUE TITLE
Not possible to easily delete multiple jobs

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs#177] opened 2015-03-02 16:01 UTC
Trying to do clean up list of the jobs I met a lack of the feature of removing multiple jobs. It would be useful to select some jobs and press a "delete selected" button. Not it takes far to many clicks to remove 10 jobs.

**Comment by gregpabian** [comment] 2015-03-03 07:12
Duplicate of #119

**Closed by gregpabian** 2015-03-03 07:12 UTC
Labels: duplicate
